[project]
name = "rl-sfc-placement"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gymnasium>=1.2.3",
    "stable-baselines3>=2.7.1",
]
